import type { Question } from './types'

export const BLOCK_A_QUESTIONS: Question[] = [
  {
    id: 'A1',
    block: 'A',
    emoji: '🎂',
    question_nl: 'Hoe oud ben je?',
    question_en: 'How old are you?',
    type: 'single_select',
    options: [
      { value: 'onder18', label_nl: 'Jonger dan 18', label_en: 'Under 18', emoji: '🎒' },
      { value: '18_24', label_nl: '18 – 24', label_en: '18 – 24', emoji: '🎓' },
      { value: '25_34', label_nl: '25 – 34', label_en: '25 – 34', emoji: '🚀' },
      { value: '35_44', label_nl: '35 – 44', label_en: '35 – 44', emoji: '💼' },
      { value: '45_54', label_nl: '45 – 54', label_en: '45 – 54', emoji: '🌿' },
      { value: '55_plus', label_nl: '55 of ouder', label_en: '55 or older', emoji: '🌅' },
    ],
  },
  {
    id: 'A2',
    block: 'A',
    emoji: '🎓',
    question_nl: 'Wat is jouw hoogst afgeronde opleidingsniveau?',
    question_en: 'What is your highest completed education level?',
    type: 'single_select',
    options: [
      { value: 'basisschool', label_nl: 'Basisschool', label_en: 'Primary school', emoji: '🏫' },
      { value: 'vmbo_mbo1', label_nl: 'VMBO / MBO 1', label_en: 'VMBO / MBO 1', emoji: '📚' },
      { value: 'mbo', label_nl: 'MBO', label_en: 'MBO', emoji: '🛠️' },
      { value: 'havo_vwo', label_nl: 'HAVO / VWO', label_en: 'HAVO / VWO', emoji: '📖' },
      { value: 'hbo', label_nl: 'HBO', label_en: 'HBO', emoji: '🎓' },
      { value: 'wo', label_nl: 'WO / Universiteit', label_en: 'University', emoji: '🏛️' },
      { value: 'anders', label_nl: 'Anders', label_en: 'Other', emoji: '🤔' },
    ],
  },
  {
    id: 'A3',
    block: 'A',
    emoji: '💼',
    question_nl: 'Wat is jouw huidige werksituatie?',
    question_en: 'What is your current work situation?',
    type: 'single_select',
    options: [
      { value: 'studerend', label_nl: 'Ik studeer nog of ben net klaar', label_en: 'Still studying or just finished', emoji: '📚' },
      { value: 'werkend_groei', label_nl: 'Ik werk en wil groeien', label_en: 'Working and want to grow', emoji: '💼' },
      { value: 'werkend_switch', label_nl: 'Ik werk maar wil iets anders', label_en: 'Working but want something different', emoji: '🔄' },
      { value: 'niet_werkend', label_nl: 'Ik werk niet, zoek een nieuwe start', label_en: 'Not working, looking for a fresh start', emoji: '⏸️' },
      { value: 'nooit_gewerkt', label_nl: 'Nog nooit betaald gewerkt', label_en: 'Never worked for pay', emoji: '🆕' },
    ],
  },
  {
    id: 'A4',
    block: 'A',
    emoji: '📖',
    question_nl: 'Welke richting heb je gestudeerd, of welke vakken vond je het leukst op school?',
    question_en: 'What did you study, or which school subjects did you enjoy most?',
    type: 'open_text',
    skippable: true,
    placeholder_nl: 'Bijv: economie, biologie, grafisch ontwerp, techniek...',
    placeholder_en: 'E.g.: economics, biology, graphic design, technology...',
  },
]

export const BLOCK_C_QUESTIONS: Question[] = [
  {
    id: 'C1',
    block: 'C',
    emoji: '🎭',
    question_nl: 'Waar zit jij op dit spectrum?',
    question_en: 'Where do you fall on this spectrum?',
    type: 'slider',
    hint_nl: 'Eerlijk antwoorden — er is geen goed of fout.',
    hint_en: 'Answer honestly — there is no right or wrong.',
    options: [
      { value: '1', label_nl: 'Heel introvert', label_en: 'Very introverted', emoji: '😌' },
      { value: '2', label_nl: 'Eerder introvert', label_en: 'Somewhat introverted', emoji: '🙂' },
      { value: '3', label_nl: 'Middenin', label_en: 'Right in the middle', emoji: '😊' },
      { value: '4', label_nl: 'Eerder extrovert', label_en: 'Somewhat extroverted', emoji: '😄' },
      { value: '5', label_nl: 'Heel extrovert', label_en: 'Very extroverted', emoji: '🎉' },
    ],
  },
  {
    id: 'C2',
    block: 'C',
    emoji: '⚡',
    question_nl: 'Wat geeft jou energie op het werk?',
    question_en: 'What gives you energy at work?',
    type: 'multi_select',
    max_select: 5,
    hint_nl: 'Kies maximaal 5. Wees eerlijk.',
    hint_en: 'Choose up to 5. Be honest.',
    options: [
      { value: 'problemen', label_nl: 'Problemen oplossen', label_en: 'Solving problems', emoji: '🧩' },
      { value: 'helpen', label_nl: 'Mensen helpen', label_en: 'Helping people', emoji: '🤝' },
      { value: 'creatief', label_nl: 'Iets creatiefs maken', label_en: 'Creating things', emoji: '🎨' },
      { value: 'data', label_nl: 'Data analyseren', label_en: 'Analysing data', emoji: '📊' },
      { value: 'presenteren', label_nl: 'Presenteren', label_en: 'Presenting', emoji: '🗣️' },
      { value: 'opbouwen', label_nl: 'Iets opbouwen', label_en: 'Building something', emoji: '🌱' },
      { value: 'leren', label_nl: 'Leren', label_en: 'Learning', emoji: '📚' },
      { value: 'resultaten', label_nl: 'Resultaten zien', label_en: 'Seeing results', emoji: '🏆' },
      { value: 'handen', label_nl: 'Met handen werken', label_en: 'Working with hands', emoji: '🔧' },
      { value: 'impact', label_nl: 'Maatschappelijke impact', label_en: 'Social impact', emoji: '🌍' },
      { value: 'doel', label_nl: 'Doel najagen', label_en: 'Chasing a goal', emoji: '🎯' },
      { value: 'multitask', label_nl: 'Veel dingen tegelijk', label_en: 'Juggling many things', emoji: '🤹' },
    ],
  },
  {
    id: 'C3',
    block: 'C',
    emoji: '😮‍💨',
    question_nl: 'Wat kost jou energie of maakt je ongelukkig?',
    question_en: 'What drains your energy or makes you unhappy?',
    type: 'multi_select',
    max_select: 5,
    options: [
      { value: 'conflicten', label_nl: 'Conflicten', label_en: 'Conflicts', emoji: '😤' },
      { value: 'herhaling', label_nl: 'Eindeloze herhaling', label_en: 'Endless repetition', emoji: '🔁' },
      { value: 'admin', label_nl: 'Veel administratie', label_en: 'Lots of admin', emoji: '📋' },
      { value: 'spotlight', label_nl: 'In de spotlights', label_en: 'Being in the spotlight', emoji: '🎤' },
      { value: 'geen_feedback', label_nl: 'Geen feedback', label_en: 'No feedback or recognition', emoji: '🔇' },
      { value: 'deadlines', label_nl: 'Harde deadlines', label_en: 'Hard deadlines', emoji: '⏰' },
      { value: 'onduidelijk', label_nl: 'Onduidelijke verwachtingen', label_en: 'Unclear expectations', emoji: '🤷' },
      { value: 'veel_mensen', label_nl: 'Veel mensen om me heen', label_en: 'Lots of people around', emoji: '👥' },
      { value: 'wisselen', label_nl: 'Constant wisselen van taken', label_en: 'Constant task switching', emoji: '🔀' },
      { value: 'geen_autonomie', label_nl: 'Geen autonomie', label_en: 'No autonomy', emoji: '📵' },
    ],
  },
  {
    id: 'C4',
    block: 'C',
    emoji: '👥',
    question_nl: 'Welke rol vervul jij van nature in een groep?',
    question_en: 'What role do you naturally take in a group?',
    type: 'single_select',
    options: [
      { value: 'bedenker', label_nl: 'De bedenker', label_en: 'The idea person', emoji: '💡' },
      { value: 'bouwer', label_nl: 'De bouwer', label_en: 'The builder', emoji: '🏗️' },
      { value: 'analist', label_nl: 'De analist', label_en: 'The analyst', emoji: '🔍' },
      { value: 'verbinder', label_nl: 'De verbinder', label_en: 'The connector', emoji: '🤝' },
      { value: 'leider', label_nl: 'De leider', label_en: 'The leader', emoji: '🧭' },
      { value: 'afmaker', label_nl: 'De afmaker', label_en: 'The finisher', emoji: '✅' },
      { value: 'helper', label_nl: 'De helper', label_en: 'The helper', emoji: '🆘' },
      { value: 'wisselend', label_nl: 'Wisselt per situatie', label_en: 'Depends on the situation', emoji: '🌀' },
    ],
  },
  {
    id: 'C5',
    block: 'C',
    emoji: '⚡',
    question_nl: 'Hoe ga jij om met werkdruk en deadlines?',
    question_en: 'How do you handle work pressure and deadlines?',
    type: 'single_select',
    options: [
      { value: 'beter_druk', label_nl: 'Ik presteer beter onder druk', label_en: 'I perform better under pressure', emoji: '⚡' },
      { value: 'beetje_druk', label_nl: 'Beetje druk prima, niet te veel', label_en: 'Some pressure is fine', emoji: '😊' },
      { value: 'rust', label_nl: 'Ik werk best met rust en ruimte', label_en: 'I work best with calm and space', emoji: '🧘' },
      { value: 'minder', label_nl: 'Druk maakt me minder effectief', label_en: 'Pressure makes me less effective', emoji: '😰' },
      { value: 'hangt_af', label_nl: 'Hangt van de situatie af', label_en: 'Really depends on the situation', emoji: '🤔' },
    ],
  },
  {
    id: 'C6',
    block: 'C',
    emoji: '🧭',
    question_nl: 'Hoe neem jij beslissingen?',
    question_en: 'How do you make decisions?',
    type: 'single_select',
    options: [
      { value: 'data', label_nl: 'Op basis van data en feiten', label_en: 'Based on data and facts', emoji: '📊' },
      { value: 'gevoel', label_nl: 'Op gevoel en intuïtie', label_en: 'On gut feeling and intuition', emoji: '❤️' },
      { value: 'bespreken', label_nl: 'Eerst bespreken met anderen', label_en: 'Discuss with others first', emoji: '🤝' },
      { value: 'afwegen', label_nl: 'Alles zorgvuldig afwegen', label_en: 'Carefully weigh everything', emoji: '⚖️' },
      { value: 'snel', label_nl: 'Snel en daadkrachtig', label_en: 'Quick and decisive', emoji: '⚡' },
    ],
  },
]

export const BLOCK_D_QUESTIONS: Question[] = [
  {
    id: 'D1',
    block: 'D',
    emoji: '💎',
    question_nl: 'Wat is voor jou het allerbelangrijkst in een baan? Kies je top 4.',
    question_en: 'What matters most to you in a job? Choose your top 4.',
    type: 'multi_select',
    max_select: 4,
    options: [
      { value: 'salaris', label_nl: 'Goed verdienen', label_en: 'Good salary', emoji: '💰' },
      { value: 'stabiliteit', label_nl: 'Stabiliteit', label_en: 'Stability and security', emoji: '🔒' },
      { value: 'groei', label_nl: 'Groeimogelijkheden', label_en: 'Growth opportunities', emoji: '🚀' },
      { value: 'zinvol', label_nl: 'Zinvol werk', label_en: 'Meaningful work', emoji: '🎯' },
      { value: 'vrijheid', label_nl: 'Vrijheid en autonomie', label_en: 'Freedom and autonomy', emoji: '🕊️' },
      { value: 'erkenning', label_nl: 'Erkenning', label_en: 'Recognition and status', emoji: '🌟' },
      { value: 'collega', label_nl: "Fijne collega's", label_en: 'Great colleagues', emoji: '🤝' },
      { value: 'creativiteit', label_nl: 'Creativiteit', label_en: 'Creativity and input', emoji: '🎨' },
      { value: 'wlb', label_nl: 'Work-life balance', label_en: 'Work-life balance', emoji: '⚖️' },
      { value: 'impact', label_nl: 'Maatschappelijke impact', label_en: 'Social impact', emoji: '🌍' },
      { value: 'leren', label_nl: 'Blijven leren', label_en: 'Continuous learning', emoji: '📚' },
      { value: 'prestaties', label_nl: 'Prestaties', label_en: 'Achievement', emoji: '🏆' },
    ],
  },
  {
    id: 'D2',
    block: 'D',
    emoji: '🏋️',
    question_nl: 'Wat past het beste bij jou?',
    question_en: 'Which fits you best?',
    type: 'slider',
    options: [
      { value: '1', label_nl: 'Volledig mentaal', label_en: 'Fully mental', emoji: '🧠' },
      { value: '2', label_nl: 'Eerder mentaal', label_en: 'Mostly mental', emoji: '💭' },
      { value: '3', label_nl: 'Mix van beide', label_en: 'Mix of both', emoji: '⚖️' },
      { value: '4', label_nl: 'Eerder fysiek', label_en: 'Mostly physical', emoji: '💪' },
      { value: '5', label_nl: 'Volledig fysiek', label_en: 'Fully physical', emoji: '🔨' },
    ],
  },
  {
    id: 'D3',
    block: 'D',
    emoji: '🏆',
    question_nl: 'Hoe weet jij dat je succesvol bent in je werk?',
    question_en: 'How do you know you\'re successful at work?',
    type: 'open_text',
    skippable: true,
    placeholder_nl: 'Bijv: als klanten blij zijn, als ik iets afmaak, als ik groei zie...',
    placeholder_en: 'E.g.: when clients are happy, when I finish something, when I see growth...',
  },
  {
    id: 'D4',
    block: 'D',
    emoji: '📖',
    question_nl: 'Hoe leer jij het liefst nieuwe dingen?',
    question_en: 'How do you prefer to learn new things?',
    type: 'multi_select',
    options: [
      { value: 'kijken', label_nl: 'Kijken hoe anderen het doen', label_en: 'Watching others', emoji: '👀' },
      { value: 'doen', label_nl: 'Gewoon beginnen en doen', label_en: 'Learning by doing', emoji: '🤸' },
      { value: 'lezen', label_nl: 'Lezen en studeren', label_en: 'Reading and studying', emoji: '📖' },
      { value: 'groep', label_nl: 'In een groep of cursus', label_en: 'Group or course', emoji: '👥' },
      { value: 'experimenteren', label_nl: 'Experimenteren', label_en: 'Experimenting', emoji: '🧪' },
      { value: 'video', label_nl: "Via video's", label_en: 'Via videos', emoji: '🎥' },
      { value: 'mentor', label_nl: 'Met een mentor', label_en: 'With a mentor', emoji: '👨‍🏫' },
    ],
  },
  {
    id: 'D5',
    block: 'D',
    emoji: '📋',
    question_nl: 'Wat past het beste bij jou qua structuur?',
    question_en: 'What suits you best when it comes to structure?',
    type: 'single_select',
    options: [
      { value: 'vast', label_nl: 'Vaste structuur en duidelijke taken', label_en: 'Fixed structure and clear tasks', emoji: '📋' },
      { value: 'mix', label_nl: 'Mix van structuur en flexibiliteit', label_en: 'Mix of structure and flexibility', emoji: '🔄' },
      { value: 'vrijheid', label_nl: 'Veel vrijheid, eigen plan maken', label_en: 'Lots of freedom, make my own plan', emoji: '🌊' },
      { value: 'dynamisch', label_nl: 'Dynamisch en onvoorspelbaar', label_en: 'Dynamic and unpredictable', emoji: '⚡' },
    ],
  },
]

export const BLOCK_E_QUESTIONS: Question[] = [
  {
    id: 'E1',
    block: 'E',
    emoji: '💶',
    question_nl: 'Welk bruto maandsalaris past bij jou?',
    question_en: 'What gross monthly salary matches your expectations?',
    type: 'single_select',
    options: [
      { value: 'onder2000', label_nl: 'Onder €2.000', label_en: 'Under €2,000', emoji: '💶' },
      { value: '2000_2800', label_nl: '€2.000 – €2.800', label_en: '€2,000 – €2,800', emoji: '💶' },
      { value: '2800_3800', label_nl: '€2.800 – €3.800', label_en: '€2,800 – €3,800', emoji: '💶' },
      { value: '3800_5000', label_nl: '€3.800 – €5.000', label_en: '€3,800 – €5,000', emoji: '💶' },
      { value: '5000_7000', label_nl: '€5.000 – €7.000', label_en: '€5,000 – €7,000', emoji: '💶' },
      { value: 'boven7000', label_nl: 'Boven €7.000', label_en: 'Above €7,000', emoji: '💶' },
      { value: 'geen_idee', label_nl: 'Nog geen idee', label_en: 'No idea yet', emoji: '🤷' },
    ],
  },
  {
    id: 'E2',
    block: 'E',
    emoji: '📄',
    question_nl: 'Wat voor contract zoek je?',
    question_en: 'What kind of contract are you looking for?',
    type: 'multi_select',
    options: [
      { value: 'vast', label_nl: 'Vast contract', label_en: 'Permanent contract', emoji: '📄' },
      { value: 'tijdelijk', label_nl: 'Tijdelijk met uitzicht op vast', label_en: 'Temp to perm', emoji: '📋' },
      { value: 'zzp', label_nl: 'ZZP / Freelance', label_en: 'ZZP / Freelance', emoji: '🔄' },
      { value: 'stage', label_nl: 'Stage of traineeship', label_en: 'Internship or traineeship', emoji: '🌱' },
      { value: 'parttime', label_nl: 'Parttime (minder dan 32u)', label_en: 'Part-time (under 32h)', emoji: '⏰' },
      { value: 'fulltime', label_nl: 'Fulltime (32-40u)', label_en: 'Full-time (32-40h)', emoji: '✅' },
    ],
  },
  {
    id: 'E3',
    block: 'E',
    emoji: '🚗',
    question_nl: 'Hoe sta jij tegenover reizen voor je werk?',
    question_en: 'How do you feel about travelling for work?',
    type: 'single_select',
    options: [
      { value: 'thuis', label_nl: 'Volledig thuiswerken', label_en: 'Fully remote', emoji: '🏠' },
      { value: 'hybrid', label_nl: 'Hybrid 2-3 dagen kantoor', label_en: 'Hybrid 2-3 days office', emoji: '🔀' },
      { value: 'vast', label_nl: 'Liefst op vaste locatie', label_en: 'Prefer fixed location', emoji: '🏢' },
      { value: 'max30', label_nl: 'Max 30 min reizen', label_en: 'Max 30 min commute', emoji: '🚗' },
      { value: 'max60', label_nl: 'Max 1 uur reizen', label_en: 'Max 1 hour commute', emoji: '🚂' },
      { value: 'internationaal', label_nl: 'Reizen prima, ook internationaal', label_en: 'Travel fine, including international', emoji: '✈️' },
    ],
  },
  {
    id: 'E4',
    block: 'E',
    emoji: '🏠',
    question_nl: 'Is er iets in jouw leven dat invloed heeft op wat voor werk mogelijk is?',
    question_en: 'Is there anything in your life that affects what work is possible for you?',
    type: 'multi_select',
    skippable: true,
    options: [
      { value: 'kinderen', label_nl: 'Jonge kinderen, flexibele tijden nodig', label_en: 'Young children, need flexible hours', emoji: '👶' },
      { value: 'mantelzorg', label_nl: 'Mantelzorgtaken', label_en: 'Caregiving responsibilities', emoji: '👴' },
      { value: 'beperking', label_nl: 'Rekening houden met beperking of gezondheid', label_en: 'Considering a disability or health condition', emoji: '♿' },
      { value: 'verhuizen', label_nl: 'Bereid te verhuizen', label_en: 'Willing to relocate', emoji: '🌍' },
      { value: 'niet_verhuizen', label_nl: 'Kan niet verhuizen', label_en: 'Cannot relocate', emoji: '🏠' },
      { value: 'geen', label_nl: 'Geen specifieke beperkingen', label_en: 'No specific constraints', emoji: '✅' },
    ],
  },
  {
    id: 'E5',
    block: 'E',
    emoji: '📅',
    question_nl: 'Wanneer zou je idealiter willen starten?',
    question_en: 'When would you ideally like to start?',
    type: 'single_select',
    options: [
      { value: 'direct', label_nl: 'Zo snel mogelijk', label_en: 'As soon as possible', emoji: '⚡' },
      { value: '1_3_mnd', label_nl: 'Binnen 1-3 maanden', label_en: 'Within 1-3 months', emoji: '📅' },
      { value: '3_6_mnd', label_nl: 'Over 3-6 maanden', label_en: 'In 3-6 months', emoji: '🗓️' },
      { value: 'orienteren', label_nl: 'Oriënterend, geen datum', label_en: 'Just exploring', emoji: '🔮' },
      { value: 'afstuderen', label_nl: 'Na afstuderen', label_en: 'After graduating', emoji: '🎓' },
    ],
  },
]

export const BLOCK_F_QUESTIONS: Question[] = [
  {
    id: 'F1',
    block: 'F',
    emoji: '🎮',
    question_nl: 'Wat doe jij het liefst in je vrije tijd?',
    question_en: 'What do you love doing in your free time?',
    type: 'open_text',
    hint_nl: 'Beschrijf het uitgebreid. Ook "Netflix kijken" zegt iets, maar details helpen ons meer.',
    hint_en: 'Describe it in detail. Even "watching Netflix" says something, but more detail helps.',
    placeholder_nl: 'Bijv: muziek maken, koken voor vrienden, dingen bouwen, DnD spelen, fietsen...',
    placeholder_en: 'E.g.: making music, cooking for friends, building things, playing DnD, cycling...',
  },
  {
    id: 'F2',
    block: 'F',
    emoji: '🏢',
    question_nl: 'Welke sectoren vind jij interessant?',
    question_en: 'Which sectors interest you?',
    type: 'chip_select',
    hint_nl: 'Kies alles wat ook maar een beetje aantrekt.',
    hint_en: 'Choose everything that even slightly appeals to you.',
    options: [
      { value: 'tech', label_nl: 'Tech', label_en: 'Tech', emoji: '💻' },
      { value: 'zorg', label_nl: 'Zorg', label_en: 'Care', emoji: '🏥' },
      { value: 'onderwijs', label_nl: 'Onderwijs', label_en: 'Education', emoji: '📚' },
      { value: 'finance', label_nl: 'Finance', label_en: 'Finance', emoji: '💰' },
      { value: 'creatief', label_nl: 'Creatief', label_en: 'Creative', emoji: '🎨' },
      { value: 'logistiek', label_nl: 'Logistiek', label_en: 'Logistics', emoji: '🚛' },
      { value: 'overheid', label_nl: 'Overheid', label_en: 'Government', emoji: '🏛️' },
      { value: 'duurzaamheid', label_nl: 'Duurzaamheid', label_en: 'Sustainability', emoji: '🌱' },
      { value: 'sport', label_nl: 'Sport', label_en: 'Sport', emoji: '⚽' },
      { value: 'wetenschap', label_nl: 'Wetenschap', label_en: 'Science', emoji: '🧪' },
      { value: 'horeca', label_nl: 'Horeca', label_en: 'Hospitality', emoji: '🍽️' },
      { value: 'toerisme', label_nl: 'Toerisme', label_en: 'Tourism', emoji: '✈️' },
      { value: 'bouw', label_nl: 'Bouw', label_en: 'Construction', emoji: '🏗️' },
      { value: 'non_profit', label_nl: 'Non-profit', label_en: 'Non-profit', emoji: '🤝' },
    ],
  },
  {
    id: 'F3',
    block: 'F',
    emoji: '💭',
    question_nl: 'Als geld geen rol speelde — wat zou jij dan elke dag willen doen?',
    question_en: 'If money were no object — what would you do every day?',
    type: 'open_text',
    placeholder_nl: 'Er zijn geen foute antwoorden. Droom gerust groot.',
    placeholder_en: 'There are no wrong answers. Dream as big as you like.',
  },
]

export const BLOCK_G_QUESTIONS: Question[] = [
  {
    id: 'G1',
    block: 'G',
    emoji: '💬',
    question_nl: 'Wat zeggen mensen die jou goed kennen over jouw kwaliteiten? Waar vragen ze jou om hulp?',
    question_en: 'What do people who know you well say about your qualities? What do they ask for your help with?',
    type: 'open_text',
    skippable: true,
    placeholder_nl: 'Bijv: vrienden vragen me altijd om raad, collega\'s zeggen dat ik goed kan uitleggen...',
    placeholder_en: 'E.g.: friends always ask my advice, colleagues say I explain things well...',
  },
  {
    id: 'G2',
    block: 'G',
    emoji: '⭐',
    question_nl: 'Wat is jouw grootste kwaliteit of talent — iets wat jou onderscheidt?',
    question_en: 'What is your greatest quality or talent — something that sets you apart?',
    type: 'open_text',
    skippable: true,
    placeholder_nl: 'Beschrijf iets wat jou écht uniek maakt...',
    placeholder_en: 'Describe something that makes you truly unique...',
  },
  {
    id: 'G3',
    block: 'G',
    emoji: '🌟',
    question_nl: 'Beschrijf in je eigen woorden wie jij bent en wat jou gelukkig maakt in je werk.',
    question_en: 'Describe in your own words who you are and what makes you happy at work.',
    type: 'open_text',
    skippable: false,
    hint_nl: 'Dit is de meest waardevolle vraag. De AI leest dit het meest zorgvuldig.',
    hint_en: 'This is the most valuable question. The AI reads this most carefully.',
    placeholder_nl: 'Beschrijf je werkstijl, wat je drijft, wat je blij maakt...',
    placeholder_en: 'Describe your work style, what drives you, what makes you happy...',
  },
]

export const BLOCK_DEFINITIONS = [
  { id: 'A', name_nl: 'Startpunt', name_en: 'Starting point', color: 'rose' as const },
  { id: 'B', name_nl: 'Werkervaring', name_en: 'Work experience', color: 'rose' as const },
  { id: 'C', name_nl: 'Persoonlijkheid', name_en: 'Personality', color: 'peach' as const },
  { id: 'D', name_nl: 'Waarden & Motivatie', name_en: 'Values & Motivation', color: 'peach' as const },
  { id: 'E', name_nl: 'Praktisch', name_en: 'Practical', color: 'sky' as const },
  { id: 'F', name_nl: 'Interesses', name_en: 'Interests', color: 'sky' as const },
  { id: 'G', name_nl: 'Vrije expressie', name_en: 'Free expression', color: 'sage' as const },
]
